### ISSUE TITLE
Emulator window freezes in 32x64

### ISSUE THREAD

**Issue by mmendelson222** [ty-porter/RGBMatrixEmulator#9] opened 2021-09-20 06:26 UTC
I'm using the emulator with the MLB scoreboard as refactored by @WardBrian .  

The emulator seems to work fine in 32x32 mode, but in 32x64 the emulator window freezes when it loses focus, rendering it useless.   I have tried a number of things including downloading the code (which solved a previous issue).  

Thanks for any help. 

![image](https://user-images.githubusercontent.com/1591186/133963069-94aedf4a-e3d3-4ba6-be21-0633606bdb70.png)

**Comment by WardBrian** [comment] 2021-09-20 12:09
This is something I noticed and it’s due to the startup image. If you delete the file (which will disable it) this issue goes away, but I’m not sure why it happens. I was meaning to file a bug report here

**Comment by ty-porter** [comment] 2021-09-20 15:36
Just so I'm understanding correctly, this is an issue with compatibility with @WardBrian's mlb-led-scoreboard fork?

**Comment by WardBrian** [comment] 2021-09-20 15:46
It comes up in my fork, I think specifically it is an issue with `matrix.SetImage` - removing that one function call from my main.py causes the problem to vanish

**Comment by mmendelson222** [comment] 2021-09-20 20:00
Excellent, guys.  Brian, I disabled the splash screen when emulating and that did the trick.  https://github.com/mmendelson222/mlb-led-scoreboard/commit/53bf210ce2cf9bb0e4317a7b55d925214cfe05e3

Thanks to both of you for the work that you've done here.

**Comment by ty-porter** [comment] 2021-09-20 20:11
@mmendelson222 I'll take a stab at seeing the root cause of the issue here, this should be enough to point me in the right direction, thanks!

**Comment by ty-porter** [comment] 2021-10-03 20:58
@WardBrian @mmendelson222 

I finally had some time to poke at this.

Long story short, the emulator uses `pygame` for rendering graphics and isn't thread-safe. The original `rpi-rgb-led-matrix` library works better in this case since it's written with thread safety in mind from the get-go. Unfortunately, I doubt that's something I can commit to supporting right now.

---

There is a workaround! The solution here is actually to ensure that all the rendering occurs on the same thread. I would advocate moving the splash screen rendering to `__render_main()` if that's suitable:

**Problematic:**
```python
    if os.path.exists(logo) and not emulated:
        logo = Image.open(logo)
        matrix.SetImage(logo.convert("RGB")) # Renders on MainThread
        logo.close()

    # Create a new data object to manage the MLB data
    # This will fetch initial data from MLB
    data = Data(config)

    # create render thread
    render = threading.Thread(target=__render_main, args=[matrix, data], name="render_thread", daemon=True)
    time.sleep(1)
    render.start() # All other rendering occurs on this thread!
```

**Works fine:**
```python
def __render_main(matrix, data):
    # Draw startup screen
    logo = "assets/mlb-w" + str(matrix.width) + "h" + str(matrix.height) + ".png"

    if os.path.exists(logo):
        logo = Image.open(logo)
        matrix.SetImage(logo.convert("RGB"))
        logo.close()

    time.sleep(2)

    MainRenderer(matrix, data).render()
```

---

Going to go ahead and close this issue as it's unable to be resolved further without ripping out the pygame dependency.

**Closed by ty-porter** 2021-10-03 20:58 UTC

**Comment by WardBrian** [comment] 2021-10-03 21:06
Valid! I'm not going to make the thread-safe change because the splash screen is intentionally drawn before the data object is created (the network calls can take a few sections, which is nice for the splash image), but it's valid to not support
